### ISSUE TITLE
How long did you spend on training? And how many GPUs?

### ISSUE THREAD

**Issue by iiiHunter** [IntuitionMachines/OrigamiNet#2]

**Comment by ASDen** [comment]
Depends a lot on the model and the dataset, but most models converge in less than 100k steps. 
The code supports training on any number of GPUs, IAM experiments can be done on a single GPU without problems.

**Comment by iiiHunter** [comment]
![Screenshot from 2020-06-21 13-04-26](https://user-images.githubusercontent.com/23523435/85217124-d6144700-b3bf-11ea-9245-cb6226ff8e84.png)
I have trained for 176k steps on IAM dataset on single GPU, but the CER is only 29? Thank you!

**Comment by ASDen** [comment]
What configuration file are you using ? (include it if you modified the defaults)
I think you may be using a small batch size...

**Comment by iiiHunter** [comment]
Thank you for your reply, it seems that a large batch size is helpful. 
One more question, do you think OrigamiNet is useful for Chinese text recognition in page level, which has 7356 classes? Thank you very much.

**Comment by ASDen** [comment]
I had good previous results with datasets with large number of classes, but didn't try chinese before.

However, I would be curious to know, so give it a shot and tell us! I would advice you to start first with the line recognizer (steps in the readme) if it works well, you can then move to the full page experiments.
