### ISSUE TITLE
Training on IAM full paragraph, but the CER is stuck at ~0.7

### ISSUE THREAD

**Issue by jackjiyh** [IntuitionMachines/OrigamiNet#5]
Hi, I was trying to train the OrigamiNet on the IAM full paragraph dataset. Due to hardware limitations, I could only use batch size of 1. But the CER is kinda stuck at ~0.7 for more than 20k steps. Is this normal? Or are there any tweaks I can make to overcome this. Thanks!
![Screenshot from 2020-08-14 09-19-30](https://user-images.githubusercontent.com/20719631/90254008-10262600-de10-11ea-9a8d-dea218e7620f.png)

**Comment by jackjiyh** [comment]
I guess it just takes a long long time to train given the hardware limitations. I am now at CER ~0.4 at 118k.

**Comment by yangyingxiang** [comment]
> I guess it just takes a long long time to train given the hardware limitations. I am now at CER ~0.4 at 118k.

I'm also experiencing slow training. Just wondering what's the final CER you got?
